### PR TITLE
Added possibility to inject as a specific authorid

### PR DESCRIPTION
**Pull request by Getty**
If you accept I will also add tests ;) (And add me to the authors list if you dont mind)

### CODE REVIEW

**Comment by Getty** [comment]
I think I really need to fork that... sad.... thought modern ways are different

**Comment by chromatic** [comment]
I like the idea, but I want to think about the implementation some more. Either way we can reuse the tests, so please go ahead and add them.

**Comment by Getty** [comment]
I want to use this soon in "production", so i'm a bit pushed here... I feel like the API that i added (and also the other pull request that is open) are both things that doesn't block future development. It would be nice if we add both (with tests) and start releasing it, moving to a newer API is not like a big deal in my eyes.

Why its relevant that its on CPAN is in this case cause i wanna use it for the DuckDuckGo own DarkPAN which is some kind of public, so i want that people can "replicate" what we can do to understand the systems, and also gain more knowledge about the perl processes if they are interested. So it would be very awesome if we come to a nice conclusion here where we wanna go.

In worst bad case, i also dont see a problem for myself, to fork it to like CPAN::Duck, and make it just an implementation for us, but i hoped that we can both stay on the same track here :-). I'm open for alternatives, or that its a "more complex" API for me now that you can make the cleaner API later, I just need the EXACTLY this code :)

**Comment by chromatic** [comment]
The user-facing API is fine. I'd like to change the customization mechanism for injected parameters though; I prefer to pass in a list of key/value pairs rather than to pass $author explicitly. I think that'll work better for multiple customization options.

As long as it's clear that the internal API will change, I'm happy to support this feature. Send me another pull request with tests and I can get this on the CPAN.

**Comment by Getty** [comment]
Thanks! Wonderful, will get on my TODO then. Can you also approve the other pull request (https://github.com/chromatic/CPAN-Dark/pull/3)? Cause I think this feature would also be important.

**Pull request merged**
